### ISSUE TITLE
Angular 14 - Unable to Resolve dependency Tree

### ISSUE THREAD

**Issue by 0xRenshaw** [almothafar/angular-signature-pad#4]
Hello, 

Is there plans to update to A14? Currently encounter the below when running npm install which means I have to add the -legacy-peer-deps 

````npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: shop-hub@0.0.0
npm ERR! Found: @angular/common@14.0.3
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^14.0.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^10.0.0 || ^11.0.0 || ^12.0.0 || ^13.0.0" from @almothafar/angular-signature-pad@4.0.1
npm ERR! node_modules/@almothafar/angular-signature-pad
npm ERR!   @almothafar/angular-signature-pad@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/tom/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tom/.npm/_logs/2022-06-29T08_40_31_216Z-debug-0.log
````

**Comment by haexyh** [comment]
I have the same issue with an minor version in my case 13.3.X

**Comment by kapsiR** [comment]
Would love to see an update to Angular v14 too (it's going to be the new LTS version soon)

@almothafar If it's enough to ["just" update the dependencies](https://github.com/almothafar/angular-signature-pad/compare/master...Deviam:angular-signature-pad:master), are there any PRs accepted?

**Comment by ntziolis** [comment]
Had a quick look at the code and there seems to be no conflict besides version. So this can be solved via adding the following to the overrides section in the package.json:

```jsonc
{
  // ...
  "dependencies": {
    "@angular/common": "~14.1.1",
    "@angular/core": "~14.1.1",
   // ...
  },
  "overrides": {
    "@almothafar/angular-signature-pad": {
      "@angular/common": "$@angular/common",
      "@angular/core": "$@angular/core"
    }
  }
}
```

Note: the `$` means it uses the version that is specified in the dependencies.

**Comment by almothafar** [comment]
Sorry, I'm not working in Angular, I'll try to fix this soon, I appreciate if anybody makes a PR if that can be faster than doing it myself.

**Comment by almothafar** [comment]
Can you please check version `5.0.1` and let me know if everything is working fine?

**Comment by kapsiR** [comment]
Thanks for the fast upgrade! 🙏

I'll let you know how it works!

**Comment by kapsiR** [comment]
@almothafar It works as expected! (Angular v14.2.1)

Thanks 🙏

**Comment by almothafar** [comment]
Fixing https://github.com/wulfsolter/angular2-signaturepad/issues/129
